### ISSUE TITLE
Podspec

### ISSUE THREAD

**Issue by Samback** [purrrminator/AKLookups#1]
Can you add cocoa pod to make installation of your library more easier?

**Comment by kevmeyer** [comment]
could you update the cocoapods version, it's still on tag 1.0.0?

**Comment by purrrminator** [comment]
@kevmeyer yes, there is no other versions released so far

**Comment by kevmeyer** [comment]
@purrrminator I was just wondering, that this version is missing the features from the sample app and the readme, i'll try it with a submodule :)
